import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the app slice
const initialState = {
  page: "settings", // Current page ('settings' or 'timer')
  fizz: "", // Fizz value input by the user, 2 to 10, inclusive
  buzz: "", // Buzz value input by the user, 2 to 10, inclusive
  fizzBuzzLocked: false, // Flag to lock Fizz and Buzz inputs after timer starts
};

// Create the app slice
const appSlice = createSlice({
  name: "app",
  initialState,
  reducers: {
    setPage(state, action) {
      state.page = action.payload;
    },
    setFizz(state, action) {
      state.fizz = action.payload;
    },
    setBuzz(state, action) {
      state.buzz = action.payload;
    },
    setFizzBuzzLocked(state, action) {
      state.fizzBuzzLocked = action.payload;
    },
    resetAppState(state) {
      state.fizz = "";
      state.buzz = "";
      state.fizzBuzzLocked = false;
      state.page = "settings";
    },
  },
});

// Export the action creators generated by createSlice
export const { setPage, setFizz, setBuzz, setFizzBuzzLocked, resetAppState } =
  appSlice.actions;

// Export the reducer to be used in the store
export default appSlice.reducer;
