import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the setting slice
const initialState = {
  error: "", // Error messages
};

// Create the setting slice
const settingSlice = createSlice({
  name: "settings",
  initialState,
  reducers: {
    setError(state, action) {
      state.error = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const { setError } = settingSlice.actions;

// Export the reducer to be used in the store
export default settingSlice.reducer;
