import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  time: 0, // Elapsed time in seconds
  running: false, // Flag to indicate if the timer is running
};

// Create the timer slice
const timerSlice = createSlice({
  name: "timer",
  initialState,
  reducers: {
    setTime(state, action) {
      state.time = action.payload;
    },
    setRunning(state, action) {
      state.running = action.payload;
    },
    resetTimerState(state) {
      state.time = 0;
      state.running = false;
    },
  },
});

// Export the action creators generated by createSlice
export const { setTime, setRunning, resetTimerState } = timerSlice.actions;

// Export the reducer to be used in the store
export default timerSlice.reducer;
